from abc import ABC
#add word_generator path to PYTHONPATH
import sys
sys.path.append('/home/ivan/pdfparser-2')

from DataGenerator.word_generator.IFont import IFont
from DataGenerator.word_generator.IVisualAugmenter import IVisualAugmenter
from DataGenerator.word_generator.IWordGenerator import IWordGenerator
from DataGenerator.word_generator.IWordRenderer import IWordRenderer
import numpy as np
from typing import List, Tuple

class ITextGenerator(ABC):
    def __init__(
        self,
        fonts: Tuple[List[IFont], np.array],
        font_sizes: Tuple[List[int], np.array],
        augmenters: List[IVisualAugmenter],
        word_generator: IWordGenerator,
        word_renderer: IWordRenderer,
        *args,
        **kwargs
    ):
        """
        Set up generator settings.
        @fonts - tuple of fonts and their PDF fucntion,
        @font_sizes - tuple of fonts sizes and their PDF fucntion,
        @augmenters - list of augmenters,
        @word_generator - IWordGenerator instance
        @word_renderer - IWordRenderer instance
        """
        pass

    def generate(self, n: int) -> List[IWordRenderer.word_render]:
        """
        Generates list of objects that generated by IWordRenderer.word_render function,
        @n - nubmer of generated samples
        """
        pass
